### ISSUE TITLE
Mouse cursor contrast

### ISSUE THREAD

**Issue by dragondave** [victorqribeiro/oldTerminal#2]
There's very low contrast between the mouse cursor and the page background: something significantly far more garish would be pretty typical for the era you're emulating.

**Comment by victorqribeiro** [comment]
![images (4)](https://user-images.githubusercontent.com/3822139/59875393-0f624300-9377-11e9-8f5d-971ee7eacff7.jpeg)
I remember getting the cursor color from that image. What would you suggest?

**Comment by victorqribeiro** [comment]
I just added an option so you can customize the color of the cursor. Just edit the css file:

```html
#main_content {
  caret-color: #FFF; /* this controls the color of the cursor */
}
```
